(add-hook 'after-init-hook #'global-flycheck-mode)
(add-to-list 'exordium-extra-pinned '(helpful . "melpa-pinned"))
(add-to-list 'exordium-extra-pinned '(py-autopep8 . "melpa-pinned"))
(add-to-list 'exordium-extra-pinned '(deft . "melpa-pinned"))
(add-to-list 'exordium-extra-pinned '(which-key . "melpa-pinned"))
(add-to-list 'exordium-extra-pinned '(python . "gnu"))
(add-to-list 'exordium-extra-pinned '(anaconda-mode . "melpa-pinned"))
(add-to-list 'exordium-extra-pinned '(company-anaconda . "melpa-pinned"))
(add-to-list 'exordium-extra-pinned '(swiper-helm . "melpa-pinned"))
