(setq exordium-helm-everywhere t)
(setq exordium-theme 'zenburn)
(setq exordium-fci-mode :prog)
(setq exordium-spell-check nil)
(setq exordium-theme-use-big-org-fonts nil)
(setq exordium-smooth-scroll exordium-osx)
