(setq exordium-helm-everywhere t)
(setq exordium-theme 'solarized-light)
(setq exordium-fci-mode :prog)
(setq exordium-fci-use-dashes :two)
;;(setq exordium-spell-check nil)
(setq exordium-theme-use-big-org-fonts nil)
;;(setq exordium-smooth-scroll exordium-osx)
(setq exordium-progress-bar t)
(setq exordium-enable-c++11-keywords :modern)
(setq exordium-extra-packages '(magit-gh-pulls))
(setq exordium-complete-mode :company)
(setq exordium-display-line-numbers t)
(setq exordium-inhibit-line-numbers-star-buffers t)
(setq exordium-inhibit-line-numbers-buffer-size (* 512 1024))
(setq exordium-theme-use-big-font nil)
(setq avy-all-windows 'all-frames)
(setq flycheck-global-modes '(not c++-mode c-mode))
