(setq exordium-desktop t)
(setq exordium-helm-everywhere t)
(setq exordium-theme 'solarized-light)
(setq exordium-fci-mode :prog)
(setq exordium-fci-use-dashes :two)
(setq exordium-progress-bar t)
(setq exordium-enable-c++11-keywords :modern)
(setq exordium-extra-packages '(magit-gh-pulls))
(setq exordium-complete-mode :company)
(setq exordium-display-line-numbers t)
(setq exordium-inhibit-line-numbers-star-buffers t)
(setq exordium-inhibit-line-numbers-buffer-size (* 512 1024))
(setq exordium-height-plus-1 1.075)
(setq exordium-height-plus-2 1.15)
(setq exordium-height-plus-3 1.225)
(setq exordium-height-plus-4 1.3)
(setq avy-all-windows 'all-frames)
(setq exordium-no-org-babel-confirm t)
(setq flycheck-global-modes '(not c++-mode c-mode))
