name: CI Tests

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '.gitignore'
  push:
    paths-ignore:
      - '**.md'
      - '.gitignore'

jobs:
  ci-tests:
    runs-on: ${{ matrix.os }}
    env:
      ci_tests: true
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            emacs_version: 27.2
          - os: macos-latest
            emacs_version: 29.1
          - os: macos-latest
            emacs_version: snapshot
    steps:
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}
      - uses: actions/checkout@v4
        with:
          # repository: 'emacs-exordium/exordium'
          repository: 'pkryger/exordium'
          path: '.emacs.d'
      - uses: actions/checkout@v4
        with:
          path: '.emacs.d/taps/commontap'
      - uses: actions/checkout@v4
        with:
          repository: 'pkryger/difftastic.el'
          path: 'gh/pkryger/difftastic.el'
      - uses: actions/checkout@v4
        with:
          repository: 'pkryger/basic-stats'
          path: 'gh/pkryger/basic-stats'
      - name: First start # So most modules are pulled in from melpa and gnu
        run: '.emacs.d/.ci/first-start.sh .emacs.d'
